// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH1EbeSnT0HTHjNSuD61zdaEWB0vyp_Ec',
    appId: '1:541060523110:android:83e5902992dab1a9bc79a7',
    messagingSenderId: '541060523110',
    projectId: 'go-kigali',
    storageBucket: 'go-kigali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoU-FU8YlM6UqDeVinxHevPj2p_r5fg1M',
    appId: '1:541060523110:ios:6b9fff2f0afed5e9bc79a7',
    messagingSenderId: '541060523110',
    projectId: 'go-kigali',
    storageBucket: 'go-kigali.firebasestorage.app',
    androidClientId: '541060523110-mq2d9uqqudeb9uol5grusod3b5i3lqmd.apps.googleusercontent.com',
    iosClientId: '541060523110-otu4dbq9k3s1escp62msljg3pgnag2hu.apps.googleusercontent.com',
    iosBundleId: 'com.example.goKigali',
  );

}